apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app          # 애플리케이션 이름
  namespace: argocd            # ArgoCD가 설치된 네임스페이스
spec:
  project: default             # ArgoCD 프로젝트 이름 (기본값: default)
  source:
    repoURL: https://github.com/dongtae99/kustomize-argoupdater.git
    targetRevision: HEAD       # 사용할 브랜치 또는 태그 (HEAD = 기본 브랜치)
    path: .                    # 리포지토리에서 리소스를 참조할 경로
  destination:
    server: https://kubernetes.default.svc  # Kubernetes 클러스터 API 서버
    namespace: default                      # 기본 네임스페이스로 배포
  syncPolicy:
    automated:
      prune: true             # 불필요한 리소스를 자동으로 삭제
      selfHeal: true          # 클러스터 상태 불일치 시 자동 복구
