
apiVersion: v1
kind: Namespace
metadata:
  name: frontend-ns

---
apiVersion: v1
kind: Namespace
metadata:
  name: backend-ns

---
apiVersion: v1
kind: Namespace
metadata:
  name: db-ns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cf
  namespace: frontend-ns
data:
  FRONTEND_PORT: "8000"
  GUESTBOOK_API_ADDR: "backend.backend-ns.svc.cluster.local:8000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-cf
  namespace: backend-ns
data:
  BACKEND_PORT: "8000"
  GUESTBOOK_DB_ADDR: "mongodb.db-ns.svc.cluster.local:27017"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-cf
  namespace: db-ns
data:
  MONGO_DB_PORT: "27017"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend-ns
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 710281024320.dkr.ecr.ap-northeast-2.amazonaws.com/ingress-kitchen:cb63dce
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: frontend-cf
              key: FRONTEND_PORT
        - name: GUESTBOOK_API_ADDR
          valueFrom:
            configMapKeyRef:
              name: frontend-cf
              key: GUESTBOOK_API_ADDR
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend-ns
spec:
  ports:
  - port: 3000
    targetPort: 8000
    nodePort: 30736
  selector:
    app: frontend
  type: NodePort # Change to NodePort if not using a cloud provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend-ns
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: imyourkm/backend:test
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-cf
              key: BACKEND_PORT
        - name: GUESTBOOK_DB_ADDR
          valueFrom:
            configMapKeyRef:
              name: backend-cf
              key: GUESTBOOK_DB_ADDR
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backend-ns
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: db-ns
  labels:
    app: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: imyourkm/mongodb:test
        ports:
        - containerPort: 27017
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: db-cf
              key: MONGO_DB_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: db-ns
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
 
