apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend-ns
spec:
  template:
    spec:
      containers:
      - name: frontend
        image: 710281024320.dkr.ecr.ap-northeast-2.amazonaws.com/ingress-kitchen:latest

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend-ns
spec:
  template:
    spec:
      containers:
      - name: backend
        image: imyourkm/backend:test
