apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy-ecr.yaml

images:
  - name: 710281024320.dkr.ecr.ap-northeast-2.amazonaws.com/ingress-kitchen
    newTag: latest

patchesStrategicMerge:
  - image-patch.yaml
